// ============================================================
// HEALTHCARE ANALYTICS — ALL DAX MEASURES REFERENCE
// Copy-paste these into Power BI Desktop
// ============================================================


// ── KPI MEASURES ──────────────────────────────────────────

Total Patients = 
COUNTROWS(patients)

Total Revenue = 
SUM(patients[TreatmentCost])

Avg Treatment Cost = 
AVERAGE(patients[TreatmentCost])

Avg Hospital Stay = 
AVERAGE(patients[HospitalStayDays])

Avg Satisfaction Score = 
AVERAGE(patients[Satisfaction])

Total Insurance Claimed = 
SUM(patients[InsuranceCovered])

Total Out Of Pocket = 
SUM(patients[OutOfPocket])


// ── READMISSION MEASURES ──────────────────────────────────

Total Readmissions = 
CALCULATE(COUNTROWS(patients), patients[Readmission] = "Yes")

Readmission Rate % = 
DIVIDE(
    CALCULATE(COUNTROWS(patients), patients[Readmission] = "Yes"),
    COUNTROWS(patients),
    0
) * 100


// ── FINANCIAL MEASURES ────────────────────────────────────

Insurance Coverage % = 
DIVIDE(
    SUM(patients[InsuranceCovered]), 
    SUM(patients[TreatmentCost]),
    0
) * 100

Out Of Pocket % = 
DIVIDE(
    SUM(patients[OutOfPocket]),
    SUM(patients[TreatmentCost]),
    0
) * 100

Pending Payments Amount = 
CALCULATE(
    SUM(patients[OutOfPocket]),
    patients[PaymentStatus] = "Pending"
)

Pending Patient Count = 
CALCULATE(
    COUNTROWS(patients),
    patients[PaymentStatus] = "Pending"
)

Revenue MoM Change = 
VAR CurrentMonth = SUM(patients[TreatmentCost])
VAR PreviousMonth = CALCULATE(
    SUM(patients[TreatmentCost]),
    DATEADD(patients[AdmissionDate], -1, MONTH)
)
RETURN
DIVIDE(CurrentMonth - PreviousMonth, PreviousMonth, 0) * 100


// ── PATIENT MEASURES ──────────────────────────────────────

Male Patients = 
CALCULATE(COUNTROWS(patients), patients[Gender] = "Male")

Female Patients = 
CALCULATE(COUNTROWS(patients), patients[Gender] = "Female")

Avg Age = 
AVERAGE(patients[Age])

Patients Above 60 = 
CALCULATE(COUNTROWS(patients), patients[Age] > 60)

High Cost Patients = 
CALCULATE(
    COUNTROWS(patients),
    patients[TreatmentCost] > AVERAGE(patients[TreatmentCost]) * 1.5
)


// ── DOCTOR MEASURES ───────────────────────────────────────

Top Doctor by Revenue = 
CALCULATE(
    FIRSTNONBLANK(patients[DoctorName], 1),
    TOPN(1, VALUES(patients[DoctorName]), [Total Revenue], DESC)
)

Top Rated Doctor = 
CALCULATE(
    FIRSTNONBLANK(doctors[DoctorName], 1),
    TOPN(1, VALUES(doctors[DoctorName]), AVERAGE(doctors[AvgRating]), DESC)
)


// ── SATISFACTION MEASURES ─────────────────────────────────

Excellent Satisfaction Count = 
CALCULATE(COUNTROWS(patients), patients[Satisfaction] = 5)

Poor Satisfaction Count = 
CALCULATE(COUNTROWS(patients), patients[Satisfaction] <= 2)

Satisfaction Index = 
DIVIDE(
    SUMX(patients, patients[Satisfaction]),
    COUNTROWS(patients) * 5,
    0
) * 100


// ── DYNAMIC TITLES (for visuals) ──────────────────────────

Selected Department Title = 
"Department: " & 
IF(
    ISFILTERED(patients[Department]),
    SELECTEDVALUE(patients[Department], "Multiple"),
    "All"
)
